name: Publish to PyPI
on:
  workflow_call:
    inputs:
      spm-version:
        description: 'SPM Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
        type: string
      matlab-version:
        description: 'MATLAB release'
        required: false
        default: 'R2024b'
        type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Check out spm-runtime
        uses: actions/checkout@v4

      - name: Install matlab-runtime
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/balbasty/matlab-runtime

      - name: Create version-specific package
        run: |
          python scripts/spm_make_runtime.py \
            --matlab-version ${{ inputs.matlab-version }} \
            --spm-version ${{ inputs.spm-version }}

      - name: Download CTF
        uses: actions/download-artifact@v4
        with:
          name: spm_${{ inputs.matlab-version }}_${{ inputs.spm-version }}.ctf

      - name: Move CTF
        run: |
          mv spm_${{ inputs.matlab-version }}_${{ inputs.spm-version }}.ctf \
             spm-runtime/spm_runtime/_spm/_spm.ctf

      - name: Install dependencies for building package
        run: python -m pip install --upgrade build

      - name: Build distribution 📦
        run: python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
