name: Release (R2024b)
description: Compile, Build, Publish on PyPI, Release on GitHub

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

env:
  MATLAB_VERSION: R2024b
  SPM_VERSION: ${{ github.event.workflow_run.name }}

# ======================================================================

jobs:

  # --------------------------------------------------------------------
  guess-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/guess_version.yml
    with:
      spm-version: ${{ env.SPM_VERSION }}

  # --------------------------------------------------------------------
  compile:
    needs: guess-version
    uses: ./.github/workflows/compile.yml
    with:
      spm-version: ${{ env.SPM_VERSION }}
      matlab-version: ${{ env.MATLAB_VERSION }}

  # --------------------------------------------------------------------
  build:
    needs: compile
    uses: ./.github/workflows/build.yml
    with:
      spm-version: ${{ env.SPM_VERSION }}
      matlab-version: ${{ env.MATLAB_VERSION }}
      main-package: false

  # --------------------------------------------------------------------
  publish-pypi:
    needs: build
    runs-on: ubuntu-latest

    environment:
      # name: pypi
      # url: https://pypi.org/p/spm-runtime

      name: testpypi
      url: https://test.pypi.org/p/spm-runtime

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download distribution
      uses: actions/download-artifact@v4
      with:
        name: spm_${{ env.SPM_VERSION }}_${{ env.MATLAB_VERSION }}.dist
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
