name: Compile and publish
on:
  workflow_dispatch:
    inputs:
      spm-version:
        description: 'SPM Commit / Branch / Tag / SHA to checkout'
        required: false
        default: 'latest'

jobs:

  compile-and-publish:

    strategy:
      fail-fast: False
      matrix:
        matlab-version: [
          "R2020a", "R2020b",
          "R2021a", "R2021b",
          "R2022a", "R2022b",
          "R2023a", "R2023b",
          "R2024a", "R2024b",
        ]

    steps:
      - name: Compile
        uses: ./.github/workflows/compile
        with:
          matlab-version: ${{ inputs.matlab-version }}
          spm-version: ${{ inputs.spm-version }}

      - name: Publish
        uses: ./.github/workflows/publish
        with:
          matlab-version: ${{ inputs.matlab-version }}
          spm-version: ${{ inputs.spm-version }}
