name: Release (R2024b)
description: Compile, Build, Publish on PyPI, Release on GitHub

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

env:
  MATLAB_VERSION: R2024b
  SPM_VERSION: ${{ github.event.workflow_run.name }}

# ======================================================================

jobs:

  # --------------------------------------------------------------------
  guess-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Guess version
        uses: ./.github/workflows/guess_version
        with:
          spm-version: ${{ env.SPM_VERSION }}

  # --------------------------------------------------------------------
  compile:
    needs: guess-version
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Compile
        uses: ./.github/workflows/compile
        with:
          matlab-version: ${{ env.MATLAB_VERSION }}
          spm-version: ${{ env.SPM_VERSION }}

  # --------------------------------------------------------------------
  publish-pypi:
    runs-on: ubuntu-latest
    needs: compile

    environment:
      # name: pypi
      # url: https://pypi.org/p/spm-runtime

      name: testpypi
      url: https://test.pypi.org/p/spm-runtime

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:

    - name: Check out
      uses: actions/checkout@v4

    - name: Build
      uses: ./.github/workflows/build
      with:
        spm-version: ${{ env.SPM_VERSION }}
        matlab-version: ${{ env.MATLAB_VERSION }}
        main-package: true

    - name: Download distribution
      uses: actions/download-artifact@v4
      with:
        name: spm_${{ env.SPM_VERSION }}_${{ env.MATLAB_VERSION }}.dist
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
